name: Push Datapack to Server

on:
  push:
    branches:
      - main  # This means the robot only triggers when you push to the main branch

jobs:
  deploy:
    name: SFTP Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fast SFTP Sync
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: './'
          server-dir: '/world/'
          protocol: sftp