
name: Push Datapack to Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: SFTP Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files to Pterodactyl
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          password: ${{ secrets.SFTP_PASSWORD }}
          sftp_only: true
          local_path: './*' 
          remote_path: '/world/' 